# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dripl
email: hello@dripl.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Experiments in building a sustainable internet business without raising investment so that we can quit our day jobs #IndieHacker
baseurl: "/land" # the subpath of your site, e.g. /blog
url: "https://alixedi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alixedi
github_username:  alixedi

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# jekyll-seo-tag defaults
tagline: >-
  Beautiful & simple mobile apps that help users pass tests
url: https://dripl.co.uk/
author:
  name: Ali Zaidi
  twitter: alixedi
  url: https://twitter.com/alixedi/
twitter:
  username: alixedi
  card: summary
logo: /assets/uploads/dripl.png
social:
  name: Ali Zaidi
  links:
    - https://twitter.com/alixedi
    - https://www.linkedin.com/in/alixedi
    - https://github.com/alixedi
google_site_verification: 9CmFl4ya9ybF5sWWb_A2f1fVwLZrR9-3w4gjQzsFTVU
locale: en_GB
