# config.yml

backend:
  # Local
  #name: git-gateway
  # Prod
  name: github
  repo: alixedi/land
  branch: main
  site_domain: quizzical-davinci-d19cc3.netlify.app
# Uncomment for local dev
#local-backend: true
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    public_folder: 'assets/uploads/'
    editor:
      preview: false
    files:
      - name: 'home'
        label: 'Home'
        file: 'index.md'
        identifier_field: permalink
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "permalink", label: "Permanent link for this page", widget: "string" }
          - { name: "color", label: "Color", widget: "color" }
          - name: "image"
            label: "Image"
            widget: "object"
            fields:
            - {name: src, label: Image, widget: image}
            - {name: alt, label: Alt text, widget: string}
            - {name: title, label: Title, widget: string}
          - name: "banner"
            label: "Banner"
            widget: "object"
            collapsed: true
            fields:
              - { name: "title", label: "Title", widget: "markdown" }
              - { name: "subtitle", label: "Subtitle", widget: "markdown" }
              - name: "image"
                label: "Image"
                widget: "object"
                fields:
                - {name: src, label: Image, widget: image}
                - {name: alt, label: Alt text, widget: string}
                - {name: title, label: Title, widget: string}
          - name: "texts"
            label: "Text Sections"
            widget: "list"
            collapsed: true
            minimize_collapsed: true
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "description", label: "Description", widget: "markdown" }
              - name: "image"
                label: "Image"
                widget: "object"
                fields:
                - {name: src, label: Image, widget: image}
                - {name: alt, label: Alt text, widget: string}
                - {name: title, label: Title, widget: string}
          - name: "products"
            label: "Products"
            widget: "list"
            collapsed: true
            minimize_collapsed: true
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "description", label: "Description", widget: "markdown" }
              - { name: "link", label: "Link", widget: "string" }
              - name: "image"
                label: "Image"
                widget: "object"
                fields:
                - {name: src, label: Image, widget: image}
                - {name: alt, label: Alt text, widget: string}
                - {name: title, label: Title, widget: string}
          - name: "cta"
            label: "Call To Action"
            widget: "object"
            collapsed: true
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "subtitle", label: "Subtitle", widget: "string" }
              - { name: 'action', label: "Action", widget: "string"}
              - { name: 'link', label: 'Link', widget: "string" }
          - name: "footer"
            label: "Footer"
            widget: "list"
            collapsed: true
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - name: "items"
                label: "Items"
                widget: "list"
                fields:
                  - { name: "name", label: "Name", widget: "string" }
                  - { name: "link", label: "Link", widget: "string" }
  - name: 'apps'
    label: 'Apps'
    folder: 'apps/'
    public_folder: '../assets/uploads/'
    identifier_field: permalink
    create: true
    editor:
      preview: false
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "app" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "permalink", label: "Permanent link for this page", widget: "string" }
      - name: "image"
        label: "Image"
        widget: "object"
        fields:
        - {name: src, label: Image, widget: image}
        - {name: alt, label: Alt text, widget: string}
        - {name: title, label: Title, widget: string}
      - { name: "color", label: "Color", widget: "color" }
      - { name: "appstore", label: "App Store Link", widget: "string" }
      - { name: "playstore", label: "Play Store Link", widget: "string" }
      - name: "banner"
        label: "Banner"
        widget: "object"
        collapsed: true
        fields:
          - { name: "title", label: "Title", widget: "markdown" }
          - { name: "subtitle", label: "Subtitle", widget: "markdown" }
          - name: "image"
            label: "Image"
            widget: "object"
            fields:
            - {name: src, label: Image, widget: image}
            - {name: alt, label: Alt text, widget: string}
            - {name: title, label: Title, widget: string}
      - name: "features"
        label: "Features"
        widget: "list"
        collapsed: true
        minimize_collapsed: true
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "markdown" }
          - name: "image"
            label: "Image"
            widget: "object"
            fields:
            - {name: src, label: Image, widget: image}
            - {name: alt, label: Alt text, widget: string}
            - {name: title, label: Title, widget: string}
      - name: "cta"
        label: "Call To Action"
        widget: "object"
        collapsed: true
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "subtitle", label: "Subtitle", widget: "string" }
      - name: "reviews"
        label: "Reviews"
        widget: "object"
        collapsed: true
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - name: "items"
            label: "Items"
            widget: "list"
            fields:
              - { name: "name", label: "Name", widget: "string" }
              - { name: "text", label: "Text", widget: "markdown" }
              - { name: "stars", label: "Stars", widget: "string" }
      - name: "faqs"
        label: "FAQs"
        widget: "list"
        collapsed: true
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "text", label: "text", widget: "markdown" }
      - name: "footer"
        label: "Footer"
        widget: "list"
        collapsed: true
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - name: "items"
            label: "Items"
            widget: "list"
            fields:
              - { name: "name", label: "Name", widget: "string" }
              - { name: "link", label: "Link", widget: "string" }
local_backend: True
